/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cashersystem;

import javax.swing.JPanel;
 import java.awt.Desktop;
import java.net.URI;
import java.net.URL;

/**
 *
 * @author KazSoftWare
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UserIcon = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        PasswordLabl = new javax.swing.JLabel();
        PasswordIcon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        resturanrName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        twitterButton = new javax.swing.JButton();
        FacebookButton = new javax.swing.JButton();
        YoutubeButton = new javax.swing.JButton();
        InestegarmButton = new javax.swing.JButton();
        GmailButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Made By Kaz Devs");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(905, 645));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));
        jPanel1.setForeground(new java.awt.Color(169, 224, 49));
        jPanel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(31, 36, 42));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_User_Shield_100px.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        UserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Male_User_35px.png"))); // NOI18N
        jPanel1.add(UserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        emailField.setBackground(new java.awt.Color(31, 36, 42));
        emailField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        emailField.setForeground(new java.awt.Color(255, 255, 255));
        emailField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        emailField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailField.setDisabledTextColor(new java.awt.Color(0, 120, 215));
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        jPanel1.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 220, 40));

        emailLabel.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(169, 224, 49));
        emailLabel.setText("   UserName");
        jPanel1.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 130, 20));

        PasswordLabl.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        PasswordLabl.setForeground(new java.awt.Color(169, 224, 49));
        PasswordLabl.setText("  Password");
        jPanel1.add(PasswordLabl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 120, 20));

        PasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Lock_35px.png"))); // NOI18N
        jPanel1.add(PasswordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 40, 40));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(169, 224, 49));
        jLabel2.setText("    Forget Password ?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 170, 30));

        LoginButton.setBackground(new java.awt.Color(169, 224, 49));
        LoginButton.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        LoginButton.setText("Sign In");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 220, 40));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(169, 224, 49));
        jLabel4.setText("Contact With Us On ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 160, 20));

        jTextField2.setBackground(new java.awt.Color(31, 36, 42));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField2.setDisabledTextColor(new java.awt.Color(31, 36, 42));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 230, 40));

        jPanel3.setBackground(new java.awt.Color(31, 36, 42));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_DOT_100px.png"))); // NOI18N
        jPanel3.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 208, -1, 80));

        resturanrName.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        resturanrName.setForeground(new java.awt.Color(169, 224, 49));
        resturanrName.setText("Kaz SoftWare");
        resturanrName.setToolTipText("");
        jPanel3.add(resturanrName, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 231, 244, 53));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(169, 224, 49));
        jLabel3.setText("    Restaurant System");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 411, 64));

        jButton3.setBackground(new java.awt.Color(31, 35, 42));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_32px.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setDefaultCapable(false);
        jButton3.setFocusable(false);
        jButton3.setRequestFocusEnabled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_30px_3.png"))); // NOI18N
        jButton3.setSelected(true);
        jButton3.setVerifyInputWhenFocusTarget(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 13, -1, 32));

        jButton4.setBackground(new java.awt.Color(31, 35, 42));
        jButton4.setForeground(new java.awt.Color(31, 35, 42));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_32px_1.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setDefaultCapable(false);
        jButton4.setPreferredSize(new java.awt.Dimension(40, 41));
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_30px_3.png"))); // NOI18N
        jButton4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_30px_3.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 13, 31, 32));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 470, 640));

        twitterButton.setBackground(new java.awt.Color(21, 25, 28));
        twitterButton.setForeground(new java.awt.Color(21, 25, 28));
        twitterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Twitter_32px.png"))); // NOI18N
        twitterButton.setToolTipText("Twitter");
        twitterButton.setBorder(null);
        twitterButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        twitterButton.setFocusPainted(false);
        twitterButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Twitter_32px_2.png"))); // NOI18N
        twitterButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Twitter_32px_2.png"))); // NOI18N
        twitterButton.setSelected(true);
        twitterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twitterButtonActionPerformed(evt);
            }
        });
        jPanel1.add(twitterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 30));

        FacebookButton.setBackground(new java.awt.Color(21, 25, 28));
        FacebookButton.setForeground(new java.awt.Color(21, 25, 28));
        FacebookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Facebook_32px_2.png"))); // NOI18N
        FacebookButton.setToolTipText("FaceBook");
        FacebookButton.setBorder(null);
        FacebookButton.setBorderPainted(false);
        FacebookButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FacebookButton.setDefaultCapable(false);
        FacebookButton.setFocusPainted(false);
        FacebookButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Facebook_32px_8.png"))); // NOI18N
        FacebookButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Facebook_32px_8.png"))); // NOI18N
        FacebookButton.setSelected(true);
        FacebookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacebookButtonActionPerformed(evt);
            }
        });
        jPanel1.add(FacebookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 40, 30));

        YoutubeButton.setBackground(new java.awt.Color(21, 25, 28));
        YoutubeButton.setForeground(new java.awt.Color(21, 25, 28));
        YoutubeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_YouTube_32px.png"))); // NOI18N
        YoutubeButton.setToolTipText("YouTube");
        YoutubeButton.setBorder(null);
        YoutubeButton.setBorderPainted(false);
        YoutubeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        YoutubeButton.setDefaultCapable(false);
        YoutubeButton.setFocusPainted(false);
        YoutubeButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_YouTube_32px.png"))); // NOI18N
        YoutubeButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_YouTube_32px_1.png"))); // NOI18N
        YoutubeButton.setSelected(true);
        YoutubeButton.setVerifyInputWhenFocusTarget(false);
        YoutubeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YoutubeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(YoutubeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 40, 30));

        InestegarmButton.setBackground(new java.awt.Color(21, 25, 28));
        InestegarmButton.setForeground(new java.awt.Color(21, 25, 28));
        InestegarmButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Instagram_32px.png"))); // NOI18N
        InestegarmButton.setToolTipText("Inestgram");
        InestegarmButton.setBorder(null);
        InestegarmButton.setBorderPainted(false);
        InestegarmButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InestegarmButton.setFocusPainted(false);
        InestegarmButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Instagram_32px_3.png"))); // NOI18N
        InestegarmButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Instagram_32px_3.png"))); // NOI18N
        InestegarmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InestegarmButtonActionPerformed(evt);
            }
        });
        jPanel1.add(InestegarmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 40, 30));

        GmailButton.setBackground(new java.awt.Color(21, 25, 28));
        GmailButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Gmail_32px_3.png"))); // NOI18N
        GmailButton.setToolTipText("Gmail");
        GmailButton.setBorder(null);
        GmailButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GmailButton.setFocusPainted(false);
        GmailButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Gmail_32px_2.png"))); // NOI18N
        GmailButton.setVerifyInputWhenFocusTarget(false);
        GmailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GmailButtonActionPerformed(evt);
            }
        });
        jPanel1.add(GmailButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleName("Made By Kaz SoftW");
        getAccessibleContext().setAccessibleParent(Logo);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_emailFieldActionPerformed

    private void FacebookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacebookButtonActionPerformed
        // TODO add your handling code here:
        try {
           
        Desktop.getDesktop().browse(new URL("https://www.facebook.com/kazem.mhmd.3/").toURI());
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_FacebookButtonActionPerformed

    private void twitterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twitterButtonActionPerformed
        // TODO add your handling code here:
        try {
           
        Desktop.getDesktop().browse(new URL("http://www.twitter.com/kazem721").toURI());
    } catch (Exception e) {
        e.printStackTrace();
    }

    }//GEN-LAST:event_twitterButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       // static LoginPage.dispose(); 
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void GmailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GmailButtonActionPerformed
        // TODO add your handling code here:
            try {
           
        Desktop.getDesktop().browse(new URL("https://mail.google.com/mail/u/0/#inbox?compose=GTvVlcRzDRBlxsXzxJjWKWvXbcPtDMRjWhPHBGvFwVcNRsHzcpzVRZSQcVVNWnRhtMNbgcDbnvKsv").toURI());
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_GmailButtonActionPerformed

    private void InestegarmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InestegarmButtonActionPerformed
        // TODO add your handling code here:
            try {
           
        Desktop.getDesktop().browse(new URL("https://www.instagram.com/asap.kaz/").toURI());
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_InestegarmButtonActionPerformed

    private void YoutubeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YoutubeButtonActionPerformed
        // TODO add your handling code here:
               try {
        Desktop.getDesktop().browse(new URL("https://shorturl.at/buH27").toURI());
    } catch (Exception e) {
        e.printStackTrace();
    }//GEN-LAST:event_YoutubeButtonActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
                //new LoginPage().setUndecorated(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FacebookButton;
    private javax.swing.JButton GmailButton;
    private javax.swing.JButton InestegarmButton;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel PasswordIcon;
    private javax.swing.JLabel PasswordLabl;
    private javax.swing.JLabel UserIcon;
    private javax.swing.JButton YoutubeButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel resturanrName;
    private javax.swing.JButton twitterButton;
    // End of variables declaration//GEN-END:variables
}
