/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cashersystem;
/**
 *
 * @author KazSoftWare
 */
public class RigsterFrom extends javax.swing.JFrame {

    /**
	 *
	 */
	/**
     * Creates new form RigsterFrom
     */
    public RigsterFrom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FirstNameLab = new javax.swing.JLabel();
        FirstNameField = new javax.swing.JTextField();
        LastNameLab = new javax.swing.JLabel();
        LastNameField = new javax.swing.JTextField();
        EmailRgLabel = new javax.swing.JLabel();
        EmailRgField = new javax.swing.JTextField();
        PassRgLab = new javax.swing.JLabel();
        PassRgField = new javax.swing.JTextField();
        UserIcon = new javax.swing.JLabel();
        ConfirmPassLab = new javax.swing.JLabel();
        ConfrimPassField = new javax.swing.JTextField();
        SingUpButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(31, 38, 42));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setSize(new java.awt.Dimension(900, 620));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));
        jPanel1.setForeground(new java.awt.Color(169, 224, 49));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(31, 36, 42));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_DOT_100px.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(169, 224, 49));
        jLabel2.setText("Kaz SoftW...");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 230, 50));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(169, 224, 49));
        jLabel3.setText("Inventory Managment");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 380, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 6, 470, 620));

        FirstNameLab.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        FirstNameLab.setForeground(new java.awt.Color(169, 224, 49));
        FirstNameLab.setText("FirstName ");
        jPanel1.add(FirstNameLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 150, 30));

        FirstNameField.setBackground(new java.awt.Color(31, 36, 42));
        FirstNameField.setForeground(new java.awt.Color(250, 250, 250));
        FirstNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        FirstNameField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        FirstNameField.setDisabledTextColor(new java.awt.Color(250, 250, 250));
        FirstNameField.setSelectionColor(new java.awt.Color(250, 250, 250));
        jPanel1.add(FirstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 162, 187, 41));

        LastNameLab.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        LastNameLab.setForeground(new java.awt.Color(169, 224, 49));
        LastNameLab.setText(" LastName ");
        jPanel1.add(LastNameLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 150, 30));

        LastNameField.setBackground(new java.awt.Color(31, 36, 42));
        LastNameField.setForeground(new java.awt.Color(250, 250, 250));
        LastNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        jPanel1.add(LastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 164, 187, 37));

        EmailRgLabel.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        EmailRgLabel.setForeground(new java.awt.Color(169, 224, 49));
        EmailRgLabel.setText(" Email");
        jPanel1.add(EmailRgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 50, 30));

        EmailRgField.setEditable(false);
        EmailRgField.setBackground(new java.awt.Color(31, 36, 48));
        EmailRgField.setForeground(new java.awt.Color(250, 250, 250));
        EmailRgField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        jPanel1.add(EmailRgField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 241, 392, 42));

        PassRgLab.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        PassRgLab.setForeground(new java.awt.Color(169, 224, 49));
        PassRgLab.setText("Password");
        jPanel1.add(PassRgLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 36));

        PassRgField.setBackground(new java.awt.Color(31, 38, 42));
        PassRgField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        jPanel1.add(PassRgField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 333, 392, 40));

        UserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_User_Shield_100px.png"))); // NOI18N
        jPanel1.add(UserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 22, -1, -1));

        ConfirmPassLab.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        ConfirmPassLab.setForeground(new java.awt.Color(169, 224, 49));
        ConfirmPassLab.setText("Confirm Password ");
        jPanel1.add(ConfirmPassLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 386, -1, -1));

        ConfrimPassField.setBackground(new java.awt.Color(31, 38, 42));
        ConfrimPassField.setForeground(new java.awt.Color(250, 250, 250));
        ConfrimPassField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        ConfrimPassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfrimPassFieldActionPerformed(evt);
            }
        });
        jPanel1.add(ConfrimPassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 413, 392, 45));

        SingUpButton.setBackground(new java.awt.Color(250, 250, 250));
        SingUpButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        SingUpButton.setText("Sign Up");
        SingUpButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 38, 42)));
        SingUpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SingUpButton.setFocusPainted(false);
        jPanel1.add(SingUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 392, 44));

        BackButton.setBackground(new java.awt.Color(21, 25, 28));
        BackButton.setForeground(new java.awt.Color(215, 210, 210));
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Back_To_32px_2.png"))); // NOI18N
        BackButton.setText("Back");
        BackButton.setBorder(null);
        BackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButton.setFocusPainted(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 80, -1));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   

    private void ConfrimPassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfrimPassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfrimPassFieldActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
         setVisible(false);
       LoginPage back=new LoginPage();
        back.setLocationRelativeTo(null);
         back.setSize(900,620);
        back.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RigsterFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RigsterFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RigsterFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RigsterFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RigsterFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel ConfirmPassLab;
    private javax.swing.JTextField ConfrimPassField;
    private javax.swing.JTextField EmailRgField;
    private javax.swing.JLabel EmailRgLabel;
    private javax.swing.JTextField FirstNameField;
    private javax.swing.JLabel FirstNameLab;
    private javax.swing.JTextField LastNameField;
    private javax.swing.JLabel LastNameLab;
    private javax.swing.JTextField PassRgField;
    private javax.swing.JLabel PassRgLab;
    private javax.swing.JButton SingUpButton;
    private javax.swing.JLabel UserIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
